#!/usr/bin/python

from facepy import GraphAPI
import json;
import csv,os, urllib,urllib2, datetime,requests,json,solr,time
from datetime import date
from datetime import datetime
from json import loads
from urllib2 import urlopen
from optparse import OptionParser
from pprint import pprint
from unidecode import unidecode
import codecs
import unicodedata
import sys, locale

# Program parameters
_page_size              = 5
_start_offset           = 0
_access_token           = None
_facebook_object_id     = 633502826728811
_solr_address           = None

# global variables
_total = 0
_startTime = datetime.now()

def buildSelectStatement(objectId,limit,offset):
        selectStatement = "SELECT id, username, fromid, likes ,text, time FROM comment "
        selectStatement += " WHERE object_id IN (" +str(objectId)+ ")"
        selectStatement += " ORDER BY time DESC LIMIT " + str(limit)
        selectStatement += " OFFSET " + str(offset)

        return selectStatement

def printComment(comment):
        print "id: "            + comment['id']
        print "text: "          + comment['text'].encode('utf-8')
        print "timestamp: " +  str(datetime.fromtimestamp(long(comment['time'])))
        print "--------------------------------------------"
        
def loadFacebookCommentsFromObjectId(objectId,limit=999,offset=1):

        response = graph.fql(buildSelectStatement(objectId,limit,offset))

        if(response.has_key('data')):
                comments = response['data']

                if len(comments) > 0:

                        for comment in comments:
                                global _total
                                _total += + 1

                                printComment(comment)

                        next_offset = offset + _page_size
                        loadFacebookCommentsFromObjectId(objectId,_page_size,next_offset)

graph = GraphAPI(_access_token)

loadFacebookCommentsFromObjectId(_facebook_object_id,_page_size,_start_offset)
        
